### ISSUE TITLE
This is obsolete?

### ISSUE THREAD

**Issue by ZiCog** [verhas/ScriptBasic#1]
It would be helpful if this repository would say, first thing, that ScriptBasic is not being maintained elsewhere and by others.

It has been very frustrating trying to track down the latest versions of ScriptBasic.

**Comment by verhas** [comment]
There is an active community at

https://www.scriptbasic.org/forum/

**Comment by ZiCog** [comment]
Thank you.

Sorry, I meant to write:

"...that ScriptBasic **is** being maintained elsewhere ..."

Yes, I know. 

That forum has a "sandbox" link to what I eventually gathered is the latest ScriptBasic development at
https://sandbox.allbasic.info:8181/scriptbasic/sb-dev/tree/master

It was very confusing when I first wanted to try ScriptBasic.

**Comment by verhas** [comment]
I added text to the `README.md`
